clone_folder: c:\Temp\projects\go\go-oraweb

environment:
  GOPATH: c:\Temp\Tools\+libraries\go

services:
  - oracle

install:
  - set PATH=%GOPATH%\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - go env
  - go version
  - go get github.com/tools/godep
  - godep get github.com/mitchellh/gox
  - godep get github.com/jteeuwen/go-bindata/...
  - godep restore

build_script:
  - godep go build

test_script:
  - godep go test -cover ./...

deploy: off